---
# Download from JIRA direct requires licence acceptance so get from s3 artefacts bucket
- name: Get JIRA Install Tarball from S3
  become: yes
  aws_s3:
    bucket: "{{ jira_artefact_bucket }}"
    object: "jira/{{ jira_filename }}-{{ jira_version }}.tar.gz"
    dest: "{{ jira_user_home_dir }}/{{ jira_filename }}-{{ jira_version }}.tar.gz"
    mode: get

- name: Register extraction destination
  become: yes
  stat:
    path: "{{ jira_user_home_dir }}/{{ jira_filename }}-{{ jira_version }}-standalone"
  register: tar_dest

- name: Extract tarball
  become: yes
  unarchive:
    src: "{{ jira_user_home_dir }}/{{ jira_filename }}-{{ jira_version }}.tar.gz"
    dest: "{{ jira_user_home_dir }}"
    copy: no
  when: not tar_dest.stat.exists

- name: Update JIRA install directory permissions
  become: yes
  file:
    path: "{{ jira_user_home_dir }}/{{ jira_filename }}-{{ jira_version }}-standalone"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: 0755
    recurse: yes

- name: Create JIRA data directory
  become: yes
  file: 
    path: "{{ jira_home }}"
    state: directory
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"